### ISSUE TITLE
origin of scenarioA

### ISSUE THREAD

**Issue by EmiliaJarochowska** [MindTheGap-ERC/StratPal#24]
The package is distributed with ScenarioA, which is referenced to Hohmann et al. (2024)
But the supplementary data https://osf.io/zbpwa/ does not contain the same object nor the code to create it.
https://github.com/MindTheGap-ERC/StratPal/blob/main/R/scenarioA.R has docstrings but no code to create such an object from the supplementary data included with the paper.
Do you have the code used to create scenarioA in `StratPal` somewhere? I am not sure if it should be in this repo, could also be in CarboCAT_utils.

**Comment by NiklasHohmann** [comment]
Now in https://github.com/MindTheGap-ERC/StratPal_data_prep
Should definitely not part of this repo, this would inflate the package, making it insubmissible to CRAN

**Comment by EmiliaJarochowska** [comment]
[like]  Jarochowska, E.B. (Emilia) reacted to your message:
________________________________
